apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started-app
  labels:
    app: getting-started-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: getting-started-app
  template:
    metadata:
      labels:
        app: getting-started-app
    spec:
      containers:
      - name: app
        image: 054037107907.dkr.ecr.us-east-1.amazonaws.com/getting-started-app:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: app-storage
          mountPath: /app/data
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-pvc
